import type { ResourceTypeDef } from "./types";
import { AZURE_LOCATIONS } from "./types";

const locOpts = AZURE_LOCATIONS;

export const RESOURCE_CATALOGUE: ResourceTypeDef[] = [
  {
    type: "azurerm_resource_group",
    label: "Resource Group",
    category: "Foundation",
    description: "Container for Azure resources",
    icon: "📁",
    defaultName: "main",
    outputs: ["id", "name", "location"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "rg-myapp-prod",
      },
      {
        key: "location",
        label: "Location",
        type: "select",
        required: true,
        options: locOpts,
        defaultValue: "westeurope",
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_virtual_network",
    label: "Virtual Network",
    category: "Networking",
    description: "Azure Virtual Network (VNet)",
    icon: "🌐",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "vnet-main",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
        description: "Usually same as resource group location",
      },
      {
        key: "address_space",
        label: "Address Space",
        type: "list",
        required: true,
        defaultValue: ["10.0.0.0/16"],
        placeholder: "10.0.0.0/16",
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_subnet",
    label: "Subnet",
    category: "Networking",
    description: "Subnet within a Virtual Network",
    icon: "🔀",
    defaultName: "default",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "default",
        existingKey: true,
        placeholder: "snet-default",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "virtual_network_name",
        label: "Virtual Network",
        type: "reference",
        required: true,
        refTypes: ["azurerm_virtual_network"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "address_prefixes",
        label: "Address Prefixes",
        type: "list",
        required: true,
        defaultValue: ["10.0.1.0/24"],
        placeholder: "10.0.1.0/24",
      },
      {
        key: "delegation",
        label: "Subnet delegation",
        type: "select",
        options: [
          { value: "", label: "None" },
          {
            value: "Microsoft.App/environments",
            label: "Microsoft.App/environments (Container Apps)",
          },
        ],
        defaultValue: "",
        description:
          "Required for Container Apps Environment infrastructure_subnet_id (azurerm 4.x). Prefer /21+ for CAE.",
      },
    ],
  },
  {
    type: "azurerm_network_security_group",
    label: "Network Security Group",
    category: "Networking",
    description: "NSG with inbound/outbound rules",
    icon: "🛡️",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "nsg-main",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "allow_ssh",
        label: "Allow SSH (22)",
        type: "boolean",
        defaultValue: true,
        description: "Adds an inbound rule allowing SSH from anywhere",
      },
      {
        key: "allow_http",
        label: "Allow HTTP (80)",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "allow_https",
        label: "Allow HTTPS (443)",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_subnet_network_security_group_association",
    label: "NSG ↔ Subnet Association",
    category: "Networking",
    description: "Associate an NSG with a subnet",
    icon: "🔗",
    defaultName: "main",
    outputs: ["id"],
    fields: [
      {
        key: "subnet_id",
        label: "Subnet",
        type: "reference",
        required: true,
        refTypes: ["azurerm_subnet"],
        refAttr: "id",
      },
      {
        key: "network_security_group_id",
        label: "Network Security Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_network_security_group"],
        refAttr: "id",
      },
    ],
  },
  {
    type: "azurerm_public_ip",
    label: "Public IP",
    category: "Networking",
    description: "Public IP address",
    icon: "📡",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "pip-main",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "allocation_method",
        label: "Allocation Method",
        type: "select",
        required: true,
        options: [
          { value: "Static", label: "Static" },
          { value: "Dynamic", label: "Dynamic" },
        ],
        defaultValue: "Static",
      },
      {
        key: "sku",
        label: "SKU",
        type: "select",
        options: [
          { value: "Standard", label: "Standard" },
          { value: "Basic", label: "Basic" },
        ],
        defaultValue: "Standard",
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_network_interface",
    label: "Network Interface",
    category: "Networking",
    description: "NIC for a virtual machine",
    icon: "🔌",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "nic-main",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "subnet_id",
        label: "Subnet",
        type: "reference",
        required: true,
        refTypes: ["azurerm_subnet"],
        refAttr: "id",
      },
      {
        key: "public_ip_address_id",
        label: "Public IP (optional)",
        type: "reference",
        required: false,
        refTypes: ["azurerm_public_ip"],
        refAttr: "id",
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_linux_virtual_machine",
    label: "Linux Virtual Machine",
    category: "Compute",
    description: "Linux VM with SSH auth",
    icon: "💻",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "vm-main",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        required: true,
        options: [
          { value: "Standard_B1s", label: "Standard_B1s (1 vCPU, 1 GB)" },
          { value: "Standard_B2s", label: "Standard_B2s (2 vCPU, 4 GB)" },
          { value: "Standard_D2s_v3", label: "Standard_D2s_v3 (2 vCPU, 8 GB)" },
          { value: "Standard_D4s_v3", label: "Standard_D4s_v3 (4 vCPU, 16 GB)" },
        ],
        defaultValue: "Standard_B2s",
      },
      {
        key: "admin_username",
        label: "Admin Username",
        type: "string",
        required: true,
        defaultValue: "azureuser",
      },
      {
        key: "admin_ssh_public_key",
        label: "SSH Public Key",
        type: "sensitive",
        required: true,
        defaultValue: "",
        description: "Emitted as a variable — never hardcoded",
        placeholder: "ssh-rsa AAAA...",
      },
      {
        key: "network_interface_ids",
        label: "Network Interface",
        type: "reference",
        required: true,
        refTypes: ["azurerm_network_interface"],
        refAttr: "id",
        description: "Primary NIC",
      },
      {
        key: "os_disk_caching",
        label: "OS Disk Caching",
        type: "select",
        options: [
          { value: "ReadWrite", label: "ReadWrite" },
          { value: "ReadOnly", label: "ReadOnly" },
          { value: "None", label: "None" },
        ],
        defaultValue: "ReadWrite",
        advanced: true,
      },
      {
        key: "os_disk_storage_account_type",
        label: "OS Disk Type",
        type: "select",
        options: [
          { value: "Standard_LRS", label: "Standard_LRS" },
          { value: "StandardSSD_LRS", label: "StandardSSD_LRS" },
          { value: "Premium_LRS", label: "Premium_LRS" },
        ],
        defaultValue: "Standard_LRS",
        advanced: true,
      },
      {
        key: "source_image_publisher",
        label: "Image Publisher",
        type: "string",
        defaultValue: "Canonical",
        advanced: true,
      },
      {
        key: "source_image_offer",
        label: "Image Offer",
        type: "string",
        defaultValue: "0001-com-ubuntu-server-jammy",
        advanced: true,
      },
      {
        key: "source_image_sku",
        label: "Image SKU",
        type: "string",
        defaultValue: "22_04-lts-gen2",
        advanced: true,
      },
      {
        key: "source_image_version",
        label: "Image Version",
        type: "string",
        defaultValue: "latest",
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_storage_account",
    label: "Storage Account",
    category: "Storage",
    description: "General-purpose storage account",
    icon: "💾",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "stmyappprod001 (lowercase, no dashes)",
        description: "3–24 chars, lowercase letters and numbers only",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "account_tier",
        label: "Account Tier",
        type: "select",
        options: [
          { value: "Standard", label: "Standard" },
          { value: "Premium", label: "Premium" },
        ],
        defaultValue: "Standard",
      },
      {
        key: "account_replication_type",
        label: "Replication",
        type: "select",
        options: [
          { value: "LRS", label: "LRS" },
          { value: "GRS", label: "GRS" },
          { value: "RAGRS", label: "RA-GRS" },
          { value: "ZRS", label: "ZRS" },
        ],
        defaultValue: "LRS",
      },
      {
        key: "account_kind",
        label: "Account Kind",
        type: "select",
        options: [
          { value: "StorageV2", label: "StorageV2" },
          { value: "BlobStorage", label: "BlobStorage" },
          { value: "BlockBlobStorage", label: "BlockBlobStorage" },
          { value: "FileStorage", label: "FileStorage" },
        ],
        defaultValue: "StorageV2",
        advanced: true,
      },
      {
        key: "min_tls_version",
        label: "Min TLS Version",
        type: "select",
        options: [
          { value: "TLS1_2", label: "TLS 1.2" },
          { value: "TLS1_0", label: "TLS 1.0" },
        ],
        defaultValue: "TLS1_2",
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_key_vault",
    label: "Key Vault",
    category: "Security",
    description: "Azure Key Vault for secrets & keys",
    icon: "🔐",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "kv-myapp-prod",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "sku_name",
        label: "SKU",
        type: "select",
        options: [
          { value: "standard", label: "Standard" },
          { value: "premium", label: "Premium" },
        ],
        defaultValue: "standard",
      },
      {
        key: "soft_delete_retention_days",
        label: "Soft Delete Retention (days)",
        type: "number",
        defaultValue: 7,
        advanced: true,
      },
      {
        key: "purge_protection_enabled",
        label: "Purge Protection",
        type: "boolean",
        defaultValue: false,
        advanced: true,
      },
      {
        key: "enable_rbac_authorization",
        label: "RBAC Authorization",
        type: "boolean",
        defaultValue: true,
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_service_plan",
    label: "App Service Plan",
    category: "App Services",
    description: "Hosting plan for Web Apps / Functions",
    icon: "📋",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "asp-myapp-prod",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "os_type",
        label: "OS Type",
        type: "select",
        required: true,
        options: [
          { value: "Linux", label: "Linux" },
          { value: "Windows", label: "Windows" },
        ],
        defaultValue: "Linux",
      },
      {
        key: "sku_name",
        label: "SKU",
        type: "select",
        required: true,
        options: [
          { value: "B1", label: "B1 (Basic)" },
          { value: "B2", label: "B2 (Basic)" },
          { value: "S1", label: "S1 (Standard)" },
          { value: "P1v3", label: "P1v3 (Premium)" },
          { value: "Y1", label: "Y1 (Consumption — Functions)" },
        ],
        defaultValue: "B1",
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_linux_web_app",
    label: "Linux Web App",
    category: "App Services",
    description: "Linux App Service (Web App)",
    icon: "🌍",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "app-myapp-prod",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "service_plan_id",
        label: "App Service Plan",
        type: "reference",
        required: true,
        refTypes: ["azurerm_service_plan"],
        refAttr: "id",
      },
      {
        key: "https_only",
        label: "HTTPS Only",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "node_version",
        label: "Node.js Version",
        type: "select",
        options: [
          { value: "20-lts", label: "Node 20 LTS" },
          { value: "18-lts", label: "Node 18 LTS" },
          { value: "", label: "None (custom)" },
        ],
        defaultValue: "20-lts",
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_mssql_server",
    label: "SQL Server",
    category: "Databases",
    description: "Azure SQL logical server",
    icon: "🗄️",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "sql-myapp-prod",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "version",
        label: "Version",
        type: "select",
        options: [
          { value: "12.0", label: "12.0" },
        ],
        defaultValue: "12.0",
      },
      {
        key: "administrator_login",
        label: "Admin Login",
        type: "string",
        required: true,
        defaultValue: "sqladmin",
      },
      {
        key: "administrator_login_password",
        label: "Admin Password",
        type: "sensitive",
        required: true,
        defaultValue: "",
        description: "Emitted as a sensitive variable — never hardcoded",
      },
      {
        key: "minimum_tls_version",
        label: "Min TLS Version",
        type: "select",
        options: [
          { value: "1.2", label: "1.2" },
          { value: "1.0", label: "1.0" },
        ],
        defaultValue: "1.2",
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_mssql_database",
    label: "SQL Database",
    category: "Databases",
    description: "Azure SQL database",
    icon: "📊",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "sqldb-myapp",
      },
      {
        key: "server_id",
        label: "SQL Server",
        type: "reference",
        required: true,
        refTypes: ["azurerm_mssql_server"],
        refAttr: "id",
      },
      {
        key: "sku_name",
        label: "SKU",
        type: "select",
        options: [
          { value: "Basic", label: "Basic" },
          { value: "S0", label: "S0" },
          { value: "S1", label: "S1" },
          { value: "S2", label: "S2" },
          { value: "P1", label: "P1" },
          { value: "GP_S_Gen5_1", label: "GP_S_Gen5_1 (Serverless)" },
        ],
        defaultValue: "Basic",
      },
      {
        key: "max_size_gb",
        label: "Max Size (GB)",
        type: "number",
        defaultValue: 2,
        advanced: true,
      },
      {
        key: "collation",
        label: "Collation",
        type: "string",
        defaultValue: "SQL_Latin1_General_CP1_CI_AS",
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },

  {
    type: "azurerm_container_registry",
    label: "Container Registry (ACR)",
    category: "Containers",
    description: "Azure Container Registry for Docker images",
    icon: "📦",
    defaultName: "main",
    outputs: ["id", "name", "login_server", "admin_username"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "myappregistry (alphanumeric only)",
        description: "5–50 alphanumeric characters, globally unique",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "sku",
        label: "SKU",
        type: "select",
        required: true,
        options: [
          { value: "Basic", label: "Basic" },
          { value: "Standard", label: "Standard" },
          { value: "Premium", label: "Premium" },
        ],
        defaultValue: "Basic",
      },
      {
        key: "admin_enabled",
        label: "Admin user enabled",
        type: "boolean",
        defaultValue: false,
        description: "Lab fallback only — prefer Managed Identity + AcrPull for Container Apps",
      },
      {
        key: "public_network_access_enabled",
        label: "Public network access",
        type: "boolean",
        defaultValue: true,
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_log_analytics_workspace",
    label: "Log Analytics Workspace",
    category: "Containers",
    description: "Workspace typically linked to Container Apps Environment",
    icon: "📈",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "log-myapp-prod",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "sku",
        label: "SKU",
        type: "select",
        options: [
          { value: "PerGB2018", label: "PerGB2018" },
          { value: "Free", label: "Free (legacy)" },
          { value: "Standalone", label: "Standalone" },
        ],
        defaultValue: "PerGB2018",
      },
      {
        key: "retention_in_days",
        label: "Retention (days)",
        type: "number",
        defaultValue: 30,
        advanced: true,
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_container_app_environment",
    label: "Container Apps Environment",
    category: "Containers",
    description: "Managed environment for Azure Container Apps",
    icon: "🏗️",
    defaultName: "main",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "cae-myapp-prod",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "log_analytics_workspace_id",
        label: "Log Analytics Workspace",
        type: "reference",
        required: false,
        refTypes: ["azurerm_log_analytics_workspace"],
        refAttr: "id",
        description: "When set, logs_destination is emitted as log-analytics",
      },
      {
        key: "infrastructure_subnet_id",
        label: "Infrastructure subnet (VNet integration)",
        type: "reference",
        required: false,
        refTypes: ["azurerm_subnet"],
        refAttr: "id",
        description:
          "azurerm 4.x: use a delegated subnet (Microsoft.App/environments). When set, a Consumption workload_profile is emitted.",
      },
      {
        key: "internal_load_balancer_enabled",
        label: "Internal load balancer",
        type: "boolean",
        defaultValue: false,
        description: "Private CAE endpoint (requires infrastructure_subnet_id)",
      },
      {
        key: "zone_redundancy_enabled",
        label: "Zone redundancy",
        type: "boolean",
        defaultValue: false,
        advanced: true,
        description: "Requires infrastructure_subnet_id",
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_container_app",
    label: "Container App",
    category: "Containers",
    description: "Azure Container App (single container template). Add multiple instances freely.",
    icon: "🐳",
    defaultName: "app",
    outputs: ["id", "name"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "ca-myapp-prod",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "container_app_environment_id",
        label: "Container Apps Environment",
        type: "reference",
        required: true,
        refTypes: ["azurerm_container_app_environment"],
        refAttr: "id",
      },
      {
        key: "revision_mode",
        label: "Revision mode",
        type: "select",
        required: true,
        options: [
          { value: "Single", label: "Single" },
          { value: "Multiple", label: "Multiple" },
        ],
        defaultValue: "Single",
      },
      {
        key: "container_name",
        label: "Container name",
        type: "string",
        required: true,
        defaultValue: "app",
      },
      {
        key: "container_image",
        label: "Container image",
        type: "string",
        required: true,
        defaultValue: "mcr.microsoft.com/k8se/quickstart:latest",
        placeholder: "mcr.microsoft.com/k8se/quickstart:latest",
        description: "Full image reference. With ACR linked, you can use repo:tag and the login server is prefixed.",
      },
      {
        key: "container_cpu",
        label: "CPU (cores)",
        type: "select",
        required: true,
        options: [
          { value: "0.25", label: "0.25" },
          { value: "0.5", label: "0.5" },
          { value: "0.75", label: "0.75" },
          { value: "1.0", label: "1.0" },
          { value: "1.25", label: "1.25" },
          { value: "1.5", label: "1.5" },
          { value: "1.75", label: "1.75" },
          { value: "2.0", label: "2.0" },
        ],
        defaultValue: "0.25",
      },
      {
        key: "container_memory",
        label: "Memory",
        type: "select",
        required: true,
        options: [
          { value: "0.5Gi", label: "0.5Gi" },
          { value: "1Gi", label: "1Gi" },
          { value: "1.5Gi", label: "1.5Gi" },
          { value: "2Gi", label: "2Gi" },
          { value: "3Gi", label: "3Gi" },
          { value: "4Gi", label: "4Gi" },
        ],
        defaultValue: "0.5Gi",
      },
      {
        key: "min_replicas",
        label: "Min replicas",
        type: "number",
        defaultValue: 0,
        advanced: true,
      },
      {
        key: "max_replicas",
        label: "Max replicas",
        type: "number",
        defaultValue: 10,
        advanced: true,
      },
      {
        key: "ingress_enabled",
        label: "Enable external ingress",
        type: "boolean",
        defaultValue: true,
        description: "Expose the app on the Container Apps environment domain",
      },
      {
        key: "ingress_target_port",
        label: "Ingress target port",
        type: "number",
        defaultValue: 80,
      },
      {
        key: "ingress_transport",
        label: "Ingress transport",
        type: "select",
        options: [
          { value: "auto", label: "auto" },
          { value: "http", label: "http" },
          { value: "http2", label: "http2" },
          { value: "tcp", label: "tcp" },
        ],
        defaultValue: "auto",
        advanced: true,
      },
      {
        key: "container_registry_id",
        label: "Container Registry (optional)",
        type: "reference",
        required: false,
        refTypes: ["azurerm_container_registry"],
        refAttr: "id",
        description: "Links registry block (login server / pull auth)",
      },
      {
        key: "acr_auth_mode",
        label: "ACR auth",
        type: "select",
        options: [
          { value: "managed_identity", label: "Managed identity (recommended)" },
          { value: "admin", label: "Admin credentials (lab fallback)" },
        ],
        defaultValue: "managed_identity",
        description: "Managed identity uses registry.identity + AcrPull; admin uses username/password secret",
      },
      {
        key: "identity_type",
        label: "Managed identity type",
        type: "select",
        options: [
          { value: "UserAssigned", label: "UserAssigned" },
          { value: "SystemAssigned", label: "SystemAssigned" },
          { value: "SystemAssigned, UserAssigned", label: "SystemAssigned, UserAssigned" },
          { value: "None", label: "None" },
        ],
        defaultValue: "UserAssigned",
      },
      {
        key: "user_assigned_identity_id",
        label: "User-assigned identity",
        type: "reference",
        required: false,
        refTypes: ["azurerm_user_assigned_identity"],
        refAttr: "id",
        description: "Required when ACR auth is Managed identity with UserAssigned",
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_user_assigned_identity",
    label: "User Assigned Identity",
    category: "Identity",
    description: "User-assigned managed identity (e.g. AcrPull for Container Apps)",
    icon: "🪪",
    defaultName: "main",
    outputs: ["id", "name", "principal_id"],
    fields: [
      {
        key: "name",
        label: "Name",
        type: "string",
        required: true,
        defaultValue: "",
        existingKey: true,
        placeholder: "id-myapp-acrpull",
      },
      {
        key: "resource_group_name",
        label: "Resource Group",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "name",
        existingKey: true,
      },
      {
        key: "location",
        label: "Location",
        type: "reference",
        required: true,
        refTypes: ["azurerm_resource_group"],
        refAttr: "location",
      },
      {
        key: "tags",
        label: "Tags",
        type: "tags",
        advanced: true,
        defaultValue: {},
      },
    ],
  },
  {
    type: "azurerm_role_assignment",
    label: "Role Assignment",
    category: "Identity",
    description: "RBAC role assignment (e.g. AcrPull on a Container Registry)",
    icon: "🔑",
    defaultName: "acr_pull",
    outputs: ["id"],
    fields: [
      {
        key: "scope",
        label: "Scope",
        type: "reference",
        required: true,
        refTypes: ["azurerm_container_registry", "azurerm_resource_group", "azurerm_key_vault", "azurerm_storage_account"],
        refAttr: "id",
        description: "Resource to grant access on",
      },
      {
        key: "role_definition_name",
        label: "Role",
        type: "select",
        required: true,
        options: [
          { value: "AcrPull", label: "AcrPull" },
          { value: "AcrPush", label: "AcrPush" },
          { value: "Reader", label: "Reader" },
          { value: "Contributor", label: "Contributor" },
          { value: "Key Vault Secrets User", label: "Key Vault Secrets User" },
        ],
        defaultValue: "AcrPull",
      },
      {
        key: "principal_id",
        label: "Principal",
        type: "reference",
        required: true,
        refTypes: ["azurerm_user_assigned_identity"],
        refAttr: "principal_id",
        description: "Usually the user-assigned identity principal_id",
      },
    ],
  },
];

export function getResourceType(type: string): ResourceTypeDef | undefined {
  return RESOURCE_CATALOGUE.find((r) => r.type === type);
}

export function getCategories(): string[] {
  const cats = new Set(RESOURCE_CATALOGUE.map((r) => r.category));
  return Array.from(cats);
}

export function getResourcesByCategory(category: string): ResourceTypeDef[] {
  return RESOURCE_CATALOGUE.filter((r) => r.category === category);
}
